[package]
name = "lubit"
version = "0.1.0"
edition = "2021"

[dependencies]
bendy = { version = "0.3.3", features = ["serde"] }
compact_str = { version = "0.7.1", features = ["serde"] }
derive_builder = "0.20.0"
reqwest = { version = "0.12.5", features = ["json", "cookies", "gzip", "rustls-tls", "native-tls-vendored", "stream"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_bencode = "0.2.4"
serde_bytes = "0.11.15"
sha1 = "0.10.6"
socket2 = "0.5.7"
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.15"
tracing = "0.1.40"
urlencoding = "2.1.3"
uuid = { version = "1.9.1", features = ["v4"] }

[dev-dependencies]
anyhow = "1.0.86"
